import type { AppState } from "./types";

export const SEED: AppState = {
  currentUserId: null,
  googleConnected: false,
  calendarEvents: [
    {
      id: "cal-1",
      title: "COMP1511 lecture",
      start: new Date(Date.now() + 86400000).toISOString(),
      end: new Date(Date.now() + 86400000 + 2 * 3600000).toISOString(),
      source: "demo",
    },
    {
      id: "cal-2",
      title: "Tutorial — stats",
      start: new Date(Date.now() + 2 * 86400000 + 10 * 3600000).toISOString(),
      end: new Date(Date.now() + 2 * 86400000 + 12 * 3600000).toISOString(),
      source: "demo",
    },
  ],
  suggestions: [],
  profiles: [
    {
      id: "u-maya",
      email: "maya.chen@student.unsw.edu.au",
      fullName: "Maya Chen",
      role: "student",
      uni: "UNSW Sydney",
      bio: "Third-year design student who also deep-cleans sharehouses faster than anyone should admit.",
      skills: ["Cleaning", "Graphic Design"],
      location: "Sydney",
      verifiedBadge: true,
      rating: 4.9,
      reviewCount: 18,
      completedTasks: 22,
      totalEarnings: 1860,
      createdAt: "2026-02-12T00:00:00.000Z",
    },
    {
      id: "u-arjun",
      email: "arjun.patel@student.unimelb.edu.au",
      fullName: "Arjun Patel",
      role: "student",
      uni: "University of Melbourne",
      bio: "CS major. I fix printers, set up routers, and tutor first-years who fear Python.",
      skills: ["Tech Help", "Tutoring"],
      location: "Melbourne",
      verifiedBadge: true,
      rating: 4.8,
      reviewCount: 11,
      completedTasks: 14,
      totalEarnings: 1290,
      createdAt: "2026-03-01T00:00:00.000Z",
    },
    {
      id: "u-sienna",
      email: "sienna.ng@student.uq.edu.au",
      fullName: "Sienna Ng",
      role: "student",
      uni: "University of Queensland",
      bio: "Has a ute, a dolly, and zero patience for IKEA instructions.",
      skills: ["Moving", "Delivery"],
      location: "Brisbane",
      verifiedBadge: false,
      rating: 4.7,
      reviewCount: 9,
      completedTasks: 12,
      totalEarnings: 980,
      createdAt: "2026-03-18T00:00:00.000Z",
    },
    {
      id: "u-priya",
      email: "priya@localstudio.co",
      fullName: "Priya Raman",
      role: "client",
      uni: undefined,
      bio: "Runs a small studio in Surry Hills. Always need extra hands around campaign week.",
      skills: [],
      location: "Sydney",
      verifiedBadge: false,
      rating: 5,
      reviewCount: 4,
      completedTasks: 6,
      totalEarnings: 0,
      createdAt: "2026-01-20T00:00:00.000Z",
    },
    {
      id: "u-tom",
      email: "tom.hayes@gmail.com",
      fullName: "Tom Hayes",
      role: "client",
      uni: undefined,
      bio: "Newtown renter. Happy to pay fairly and not make you guess the brief.",
      skills: [],
      location: "Sydney",
      verifiedBadge: false,
      rating: 4.6,
      reviewCount: 3,
      completedTasks: 3,
      totalEarnings: 0,
      createdAt: "2026-04-02T00:00:00.000Z",
    },
  ],
  tasks: [
    {
      id: "t-1",
      title: "End-of-lease clean — Redfern sharehouse",
      description:
        "Two-bed terrace. Oven, bathrooms, windows. Bond inspection Friday. Bring your own products or rent a kit on SideQuest.",
      category: "Cleaning",
      budget: 180,
      location: "Sydney",
      deadline: "2026-09-05",
      status: "open",
      clientId: "u-tom",
      createdAt: "2026-08-20T09:00:00.000Z",
    },
    {
      id: "t-2",
      title: "Same-day parcel run UNSW → CBD",
      description:
        "Need a portfolio dropped at a client office before 4pm. Compact car or bike is fine.",
      category: "Delivery",
      budget: 45,
      location: "Sydney",
      deadline: "2026-08-30",
      status: "open",
      clientId: "u-priya",
      createdAt: "2026-08-28T01:00:00.000Z",
    },
    {
      id: "t-3",
      title: "First-year stats tutoring (3 sessions)",
      description:
        "My sibling starts uni and is drowning in hypothesis tests. Prefer someone who’s actually taught it.",
      category: "Tutoring",
      budget: 160,
      location: "Melbourne",
      deadline: "2026-09-12",
      status: "open",
      clientId: "u-priya",
      createdAt: "2026-08-22T00:00:00.000Z",
    },
    {
      id: "t-4",
      title: "Club ball poster + Instagram set",
      description:
        "Need a chic poster, story templates, and a ticket graphic. We’ll credit you everywhere.",
      category: "Graphic Design",
      budget: 220,
      location: "Sydney",
      deadline: "2026-09-08",
      status: "in_progress",
      clientId: "u-priya",
      hiredStudentId: "u-maya",
      createdAt: "2026-08-10T00:00:00.000Z",
    },
    {
      id: "t-5",
      title: "Move a studio apartment — South Bank",
      description:
        "One bedroom, lots of plants. Stairs, no lift. Ute preferred.",
      category: "Moving",
      budget: 250,
      location: "Brisbane",
      deadline: "2026-09-03",
      status: "open",
      clientId: "u-tom",
      createdAt: "2026-08-25T00:00:00.000Z",
    },
    {
      id: "t-6",
      title: "Home office Wi-Fi + printer setup",
      description:
        "Mesh router, AirPrint, and a Windows laptop that refuses to see the printer.",
      category: "Tech Help",
      budget: 90,
      location: "Melbourne",
      deadline: "2026-09-01",
      status: "open",
      clientId: "u-priya",
      createdAt: "2026-08-26T00:00:00.000Z",
    },
    {
      id: "t-7",
      title: "Weekly fridge + bathroom tidy",
      description:
        "Ongoing Friday mornings. Small apartment, 90 minutes max.",
      category: "Cleaning",
      budget: 70,
      location: "Sydney",
      deadline: "2026-09-20",
      status: "completed",
      clientId: "u-tom",
      hiredStudentId: "u-maya",
      createdAt: "2026-07-01T00:00:00.000Z",
    },
    {
      id: "t-8",
      title: "Help load a market stall van",
      description:
        "Saturday 6am. Heavy crates, two hours, coffee on us.",
      category: "Moving",
      budget: 80,
      location: "Melbourne",
      deadline: "2026-08-31",
      status: "open",
      clientId: "u-tom",
      createdAt: "2026-08-27T00:00:00.000Z",
    },
  ],
  applications: [
    {
      id: "a-1",
      taskId: "t-1",
      studentId: "u-maya",
      message: "Done dozens of end-of-lease jobs. I can do Friday morning and bring a steam mop.",
      status: "pending",
      createdAt: "2026-08-21T00:00:00.000Z",
    },
    {
      id: "a-2",
      taskId: "t-4",
      studentId: "u-maya",
      message: "I design for three campus clubs already — can send a moodboard tonight.",
      status: "hired",
      createdAt: "2026-08-11T00:00:00.000Z",
    },
    {
      id: "a-3",
      taskId: "t-6",
      studentId: "u-arjun",
      message: "Mesh + AirPrint is my whole personality. Can do Thursday after 4.",
      status: "pending",
      createdAt: "2026-08-27T00:00:00.000Z",
    },
    {
      id: "a-4",
      taskId: "t-7",
      studentId: "u-maya",
      message: "Happy to lock a Friday slot.",
      status: "hired",
      createdAt: "2026-07-02T00:00:00.000Z",
    },
  ],
  reviews: [
    {
      id: "r-1",
      taskId: "t-7",
      fromId: "u-tom",
      toId: "u-maya",
      rating: 5,
      comment: "Place looked new. On time, no fuss.",
      createdAt: "2026-07-20T00:00:00.000Z",
    },
    {
      id: "r-2",
      taskId: "t-7",
      fromId: "u-maya",
      toId: "u-tom",
      rating: 5,
      comment: "Clear brief, paid fast, left snacks.",
      createdAt: "2026-07-20T00:00:00.000Z",
    },
  ],
  equipment: [
    {
      id: "e-1",
      name: "Steam mop + cleaning caddy",
      category: "Cleaning",
      dailyRate: 18,
      available: true,
      description: "Campus pickup at Kensington. Includes cloths and a bottle of concentrate.",
      location: "Sydney",
    },
    {
      id: "e-2",
      name: "Pressure washer",
      category: "Cleaning",
      dailyRate: 35,
      available: true,
      description: "Electric unit, 8m hose. Not for third-floor balconies.",
      location: "Sydney",
    },
    {
      id: "e-3",
      name: "Dolly + moving blankets",
      category: "Moving",
      dailyRate: 22,
      available: true,
      description: "Fits in a hatchback. Blankets for furniture and a roll of tape.",
      location: "Brisbane",
    },
    {
      id: "e-4",
      name: "DSLR + 50mm lens",
      category: "Graphic Design",
      dailyRate: 40,
      available: true,
      description: "Canon body, charged batteries, 32GB card. For events and product shots.",
      location: "Melbourne",
    },
    {
      id: "e-5",
      name: "Drill driver kit",
      category: "Tech Help",
      dailyRate: 15,
      available: false,
      description: "Currently out with a student until Monday.",
      location: "Sydney",
    },
    {
      id: "e-6",
      name: "Cargo crate bike bags",
      category: "Delivery",
      dailyRate: 12,
      available: true,
      description: "Waterproof panniers. Pickup near Central.",
      location: "Sydney",
    },
  ],
  bookings: [
    {
      id: "b-1",
      equipmentId: "e-5",
      studentId: "u-arjun",
      startDate: "2026-08-28",
      endDate: "2026-09-01",
      status: "booked",
    },
  ],
};

export const TRUST_STATS = {
  tasksCompleted: 1240,
  activeStudents: 3800,
  avgEarnings: 87,
};
